import Head from 'next/head'
import TypeIt from "typeit-react";
import styles from '../styles/Home.module.css'

export default function Home() {
  const Strong = ({children}) => {
    return <strong style={{fontWeight: 'bold'}}>{children}</strong>
}
  const strings = ['Wake up Neo...', 'The Matrix has you...', 'Follow the white rabbit.', 'Knock, knock, Neo.']
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <TypeIt
          getBeforeInit={(instance) => {
            instance
            .type(strings[0])
            .pause(750)
            .delete(strings[0].length)
            .pause(500)
            .type(strings[1])
            .pause(750)
            .delete(strings[1].length)
            .pause(500)
            .type(strings[2])
            .pause(750)
            .delete(strings[2].length)
            .pause(500)
            .type(strings[3])
            .pause(750)
            .delete(strings[3].length)
            .pause(500);

            return instance;
          }}
        />
      </main>
    </>
  )
}
